-- CREATE THE CURSOPRACTICOSQL DATABASE
CREATE DATABASE CURSOPRACTICOSQL;

-- USE THE NEWLY CREATED DATABASE
USE CURSOPRACTICOSQL;

-- CREATE TABLE FOR STUDENTS
CREATE TABLE STUDENTS (
    STUDENTID INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    AGE INT,
    EMAIL VARCHAR(100),
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

-- CREATE TABLE FOR INSTRUCTORS
CREATE TABLE INSTRUCTORS (
    INSTRUCTORID INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    EMAIL VARCHAR(100),
    SALARY DECIMAL(10, 2), 
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

-- CREATE TABLE FOR COURSES
CREATE TABLE COURSES (
    COURSEID INT PRIMARY KEY AUTO_INCREMENT,
    COURSENAME VARCHAR(100),
    DESCRIPTION TEXT,
    INSTRUCTORID INT,
    DURATIONHOURS INT,
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (INSTRUCTORID) REFERENCES INSTRUCTORS(INSTRUCTORID)
);

CREATE TABLE STUDENT_COURSE (
    STUDENT_COURSE_ID INT PRIMARY KEY AUTO_INCREMENT,
    STUDENTID INT,
    COURSEID INT,
    ENROLLMENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (STUDENTID) REFERENCES STUDENTS(STUDENTID),
    FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID)
);
