-- CREATE THE practica22 DATABASE
CREATE DATABASE practica24;

-- USE THE NEWLY CREATED DATABASE
USE practica24;

-- CREATE TABLE FOR productos
CREATE TABLE productos (
    producto_id INTEGER PRIMARY KEY NOT NULL,
    nombre VARCHAR(50),
    marca_id INT,
    precio DECIMAL(10,2),
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (marca_id) REFERENCES marcas(marca_id)
);

-- CREATE TABLE FOR marcas
CREATE TABLE marcas (
    marca_id INTEGER PRIMARY KEY NOT NULL,
    nombre VARCHAR(50),
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);